
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class symJAVA {
  /* terminals */
  public static final int CHARV = 52;
  public static final int ASIGNAR = 57;
  public static final int POT = 40;
  public static final int POR = 37;
  public static final int CHAR = 6;
  public static final int UMINUS = 59;
  public static final int XOR = 32;
  public static final int CASE = 14;
  public static final int RESTA = 36;
  public static final int PRIVATE = 62;
  public static final int CONTINUE = 16;
  public static final int INT = 3;
  public static final int LLAVE_C = 49;
  public static final int LLAVE_A = 48;
  public static final int FOR = 18;
  public static final int NOT = 34;
  public static final int AND = 29;
  public static final int IGUAL = 22;
  public static final int NAND = 30;
  public static final int NOR = 33;
  public static final int OR = 31;
  public static final int DOS_P = 46;
  public static final int INC = 42;
  public static final int SUMA = 35;
  public static final int IF = 11;
  public static final int ID = 50;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 21;
  public static final int CLASE = 9;
  public static final int error = 1;
  public static final int MAYOR_I = 26;
  public static final int COMA = 47;
  public static final int NULO = 28;
  public static final int MENOR = 25;
  public static final int PAR_C = 54;
  public static final int MOD = 39;
  public static final int PAR_A = 53;
  public static final int MENOR_I = 27;
  public static final int BREAK = 15;
  public static final int INTV = 55;
  public static final int VOID = 10;
  public static final int SWITCH = 13;
  public static final int MAYOR = 24;
  public static final int ELSE = 12;
  public static final int ERRORLEX = 58;
  public static final int WHILE = 19;
  public static final int BOOLEANV = 8;
  public static final int SUMA_S = 43;
  public static final int DEFAULT = 17;
  public static final int PUBLIC = 61;
  public static final int FLOAT = 4;
  public static final int EXTENDS = 2;
  public static final int PUNTOC = 60;
  public static final int STRING = 7;
  public static final int DIFF = 23;
  public static final int FLOATV = 56;
  public static final int COR_C = 45;
  public static final int DEC = 41;
  public static final int COR_A = 44;
  public static final int ENTRE = 38;
  public static final int STRINGV = 51;
  public static final int DO = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXTENDS",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "BOOLEANV",
  "CLASE",
  "VOID",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "BREAK",
  "CONTINUE",
  "DEFAULT",
  "FOR",
  "WHILE",
  "DO",
  "RETURN",
  "IGUAL",
  "DIFF",
  "MAYOR",
  "MENOR",
  "MAYOR_I",
  "MENOR_I",
  "NULO",
  "AND",
  "NAND",
  "OR",
  "XOR",
  "NOR",
  "NOT",
  "SUMA",
  "RESTA",
  "POR",
  "ENTRE",
  "MOD",
  "POT",
  "DEC",
  "INC",
  "SUMA_S",
  "COR_A",
  "COR_C",
  "DOS_P",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "ID",
  "STRINGV",
  "CHARV",
  "PAR_A",
  "PAR_C",
  "INTV",
  "FLOATV",
  "ASIGNAR",
  "ERRORLEX",
  "UMINUS",
  "PUNTOC",
  "PUBLIC",
  "PRIVATE"
  };
}

